2018-03-09 16:34:18,667 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:not master
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: not master
2018-03-09 16:34:18,675 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:not master
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: not master
2018-03-09 16:35:22,537 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:35:27,545 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:36:22,782 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:36:27,789 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:37:22,875 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:37:27,885 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:38:22,726 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:38:27,737 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:39:23,385 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:39:28,397 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:40:23,969 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:40:28,981 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:41:22,774 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:41:27,785 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:42:22,586 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:42:27,597 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:43:23,303 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:43:28,315 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:44:22,579 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:44:27,589 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:45:22,552 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:45:27,563 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:46:22,788 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:46:27,799 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:47:22,927 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:47:27,937 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:48:22,713 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:48:27,721 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:49:23,583 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:49:28,592 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:50:23,097 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:50:28,105 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:51:24,373 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:51:29,381 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:52:23,264 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:52:28,273 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:53:22,650 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:53:27,663 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:54:22,962 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:54:27,970 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:55:22,723 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:55:27,731 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:57:54,857 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 16:57:59,866 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 17:01:20,027 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 17:01:25,033 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 17:04:24,215 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 17:04:29,225 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 17:08:04,322 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 17:08:09,333 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 17:10:44,389 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 17:10:49,399 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 17:14:03,306 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 17:14:08,317 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 17:17:03,525 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 17:17:08,532 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 17:20:15,215 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 17:20:20,230 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 17:23:50,359 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
2018-03-09 17:23:55,366 mongo_db.py[line:913] ERROR mongo_db.save func Error,原因:could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/mongo_db.py", line 904, in save
    save_id = ses.save(save_dict)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 2481, in save
    collation=collation)
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/collection.py", line 767, in _update
    _check_write_command_response([(0, result)])
  File "/home/web/my_env/lib/python3.5/site-packages/pymongo/helpers.py", line 315, in _check_write_command_response
    raise WriteError(error.get("errmsg"), error.get("code"), error)
pymongo.errors.WriteError: could not find host matching read preference { mode: "primary", tags: [ {} ] } for set shard1
