2017-10-13 14:15:45,063 handlers.py[line:104] ERROR NoneType

2017-10-13 14:38:53,424 handlers.py[line:104] ERROR NoneType

2017-10-13 14:39:22,386 handlers.py[line:104] ERROR NoneType

2017-10-13 14:42:00,212 handlers.py[line:104] ERROR NoneType

2017-10-13 14:42:00,238 handlers.py[line:104] ERROR NoneType

2017-10-13 14:42:00,238 handlers.py[line:104] ERROR NoneType

2017-10-13 14:42:01,106 handlers.py[line:104] ERROR NoneType

2017-10-13 14:45:45,523 handlers.py[line:104] ERROR NoneType

2017-10-13 14:46:20,197 handlers.py[line:104] ERROR NoneType

2017-10-13 15:15:40,370 handlers.py[line:104] ERROR NoneType

2017-10-13 15:19:02,063 handlers.py[line:104] ERROR NoneType

2017-10-13 15:32:06,256 handlers.py[line:104] ERROR NoneType

2017-10-13 15:34:11,185 handlers.py[line:104] ERROR NoneType

2017-10-13 15:37:00,129 handlers.py[line:104] ERROR NoneType

2017-10-13 15:48:06,904 handlers.py[line:104] ERROR NoneType

2017-10-13 16:01:11,010 handlers.py[line:104] ERROR NoneType

2017-10-13 16:08:31,874 handlers.py[line:104] ERROR NoneType

2017-10-13 16:08:31,876 handlers.py[line:104] ERROR NoneType

2017-10-13 16:31:43,107 handlers.py[line:104] ERROR NoneType

2017-10-13 16:59:43,452 handlers.py[line:104] ERROR NoneType

2017-10-13 17:19:42,416 handlers.py[line:104] ERROR NoneType

2017-10-13 17:24:36,324 handlers.py[line:104] ERROR NoneType

2017-10-13 18:53:38,112 handlers.py[line:104] ERROR NoneType

2017-10-13 19:10:21,107 handlers.py[line:104] ERROR NoneType

2017-10-13 19:23:29,381 handlers.py[line:104] ERROR NoneType

2017-10-13 19:26:40,361 handlers.py[line:104] ERROR NoneType

2017-10-13 19:49:23,919 handlers.py[line:104] ERROR NoneType

2017-10-13 19:49:40,863 handlers.py[line:104] ERROR NoneType

2017-10-13 19:50:48,444 handlers.py[line:104] ERROR NoneType

2017-10-13 19:55:16,977 handlers.py[line:104] ERROR NoneType

2017-10-13 19:59:43,196 handlers.py[line:104] ERROR NoneType

2017-10-13 20:06:02,687 handlers.py[line:104] ERROR NoneType

2017-10-13 20:31:40,462 handlers.py[line:104] ERROR NoneType

2017-10-13 20:42:57,056 handlers.py[line:104] ERROR NoneType

2017-10-13 20:42:57,987 handlers.py[line:104] ERROR NoneType

2017-10-13 20:48:17,435 handlers.py[line:104] ERROR NoneType

2017-10-13 20:55:41,645 handlers.py[line:104] ERROR NoneType

2017-10-13 21:05:41,996 handlers.py[line:104] ERROR NoneType

2017-10-13 21:09:28,974 handlers.py[line:104] ERROR NoneType

2017-10-13 21:54:23,176 handlers.py[line:104] ERROR NoneType

2017-10-13 21:54:23,689 handlers.py[line:104] ERROR NoneType

2017-10-13 21:54:24,091 handlers.py[line:104] ERROR NoneType

2017-10-13 21:57:53,349 handlers.py[line:104] ERROR NoneType

2017-10-13 21:57:53,592 handlers.py[line:104] ERROR NoneType

2017-10-13 21:57:54,511 handlers.py[line:104] ERROR NoneType

2017-10-14 00:34:20,188 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-10-14 05:14:00,878 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-10-14 05:40:32,672 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserError: invalid constant string

2017-10-14 05:40:33,147 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-10-14 05:40:34,073 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-10-14 05:40:34,549 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-10-14 05:40:35,478 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-10-14 05:40:36,430 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-10-14 05:40:36,898 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-10-14 05:40:37,878 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-10-14 05:40:39,333 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-10-14 05:40:40,293 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-10-14 05:40:40,770 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-10-14 05:40:41,715 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidURLError: invalid URL

2017-10-14 05:40:42,672 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-10-14 05:40:43,618 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-10-14 05:40:44,535 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-10-14 05:40:45,456 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-10-14 05:40:46,399 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-10-14 09:01:44,730 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-10-14 10:32:08,595 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-10-14 10:55:41,315 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

