2017-10-08 02:12:19,190 server.py[line:206] INFO 
2017-10-08 02:58:57,541 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-10-08 02:58:57,542 server.py[line:298] INFO 
2017-10-08 04:51:36,547 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-10-08 04:51:36,548 server.py[line:298] INFO 
2017-10-08 17:31:38,151 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-10-08 17:31:38,152 server.py[line:298] INFO 
2017-10-08 22:57:17,106 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-10-08 22:57:17,107 server.py[line:298] INFO 
