2017-11-29 09:12:06,297 handlers.py[line:104] ERROR NoneType

2017-11-29 09:15:09,725 handlers.py[line:104] ERROR NoneType

2017-11-29 09:15:09,730 handlers.py[line:104] ERROR NoneType

2017-11-29 09:17:11,146 handlers.py[line:104] ERROR NoneType

2017-11-29 09:17:11,148 handlers.py[line:104] ERROR NoneType

2017-11-29 09:23:15,456 handlers.py[line:104] ERROR NoneType

2017-11-29 09:23:15,456 handlers.py[line:104] ERROR NoneType

2017-11-29 09:25:17,797 handlers.py[line:104] ERROR NoneType

2017-11-29 09:25:17,798 handlers.py[line:104] ERROR NoneType

2017-11-29 09:26:18,861 handlers.py[line:104] ERROR NoneType

2017-11-29 09:28:19,680 handlers.py[line:104] ERROR NoneType

2017-11-29 09:28:19,682 handlers.py[line:104] ERROR NoneType

2017-11-29 09:30:21,103 handlers.py[line:104] ERROR NoneType

2017-11-29 09:31:24,828 handlers.py[line:104] ERROR NoneType

2017-11-29 09:34:27,446 handlers.py[line:104] ERROR NoneType

2017-11-29 09:35:28,154 handlers.py[line:104] ERROR NoneType

2017-11-29 09:40:10,109 handlers.py[line:104] ERROR NoneType

2017-11-29 09:40:11,175 handlers.py[line:104] ERROR NoneType

2017-11-29 09:42:13,809 handlers.py[line:104] ERROR NoneType

2017-11-29 09:42:13,811 handlers.py[line:104] ERROR NoneType

2017-11-29 09:42:13,811 handlers.py[line:104] ERROR NoneType

2017-11-29 09:45:16,062 handlers.py[line:104] ERROR NoneType

2017-11-29 09:46:16,791 handlers.py[line:104] ERROR NoneType

2017-11-29 09:46:16,795 handlers.py[line:104] ERROR NoneType

2017-11-29 09:48:18,227 handlers.py[line:104] ERROR NoneType

2017-11-29 09:48:18,232 handlers.py[line:104] ERROR NoneType

2017-11-29 09:51:20,323 handlers.py[line:104] ERROR NoneType

2017-11-29 09:51:20,326 handlers.py[line:104] ERROR NoneType

2017-11-29 09:53:21,765 handlers.py[line:104] ERROR NoneType

2017-11-29 09:57:24,813 handlers.py[line:104] ERROR NoneType

2017-11-29 09:57:24,815 handlers.py[line:104] ERROR NoneType

2017-11-29 10:00:26,936 handlers.py[line:104] ERROR NoneType

2017-11-29 10:00:26,939 handlers.py[line:104] ERROR NoneType

2017-11-29 10:03:29,063 handlers.py[line:104] ERROR NoneType

2017-11-29 10:03:29,068 handlers.py[line:104] ERROR NoneType

2017-11-29 10:06:31,301 handlers.py[line:104] ERROR NoneType

2017-11-29 10:08:32,717 handlers.py[line:104] ERROR NoneType

2017-11-29 10:08:46,660 handlers.py[line:104] ERROR NoneType

2017-11-29 10:09:47,912 handlers.py[line:104] ERROR NoneType

2017-11-29 10:10:48,693 handlers.py[line:104] ERROR NoneType

2017-11-29 10:10:48,697 handlers.py[line:104] ERROR NoneType

2017-11-29 12:24:43,029 handlers.py[line:104] ERROR NoneType

2017-11-29 15:07:01,757 handlers.py[line:104] ERROR NoneType

2017-11-29 15:07:04,307 handlers.py[line:104] ERROR NoneType

2017-11-29 15:10:26,615 handlers.py[line:104] ERROR NoneType

2017-11-29 15:13:07,203 handlers.py[line:104] ERROR NoneType

2017-11-29 15:14:08,116 handlers.py[line:104] ERROR NoneType

2017-11-29 15:17:49,245 handlers.py[line:104] ERROR NoneType

2017-11-29 15:20:57,232 handlers.py[line:104] ERROR NoneType

2017-11-29 15:21:58,386 handlers.py[line:104] ERROR NoneType

2017-11-29 15:22:00,321 handlers.py[line:104] ERROR NoneType

2017-11-29 15:23:00,625 handlers.py[line:104] ERROR NoneType

2017-11-29 15:24:01,305 handlers.py[line:104] ERROR NoneType

2017-11-29 15:25:02,018 handlers.py[line:104] ERROR NoneType

2017-11-29 15:25:02,020 handlers.py[line:104] ERROR NoneType

2017-11-29 15:26:02,696 handlers.py[line:104] ERROR NoneType

2017-11-29 15:26:02,698 handlers.py[line:104] ERROR NoneType

2017-11-29 15:27:03,377 handlers.py[line:104] ERROR NoneType

2017-11-29 15:27:06,290 handlers.py[line:104] ERROR NoneType

2017-11-29 15:27:06,292 handlers.py[line:104] ERROR NoneType

2017-11-29 15:28:04,048 handlers.py[line:104] ERROR NoneType

2017-11-29 15:28:26,019 handlers.py[line:104] ERROR NoneType

2017-11-29 15:28:26,027 handlers.py[line:104] ERROR NoneType

2017-11-29 15:28:26,028 handlers.py[line:104] ERROR NoneType

2017-11-29 15:29:04,756 handlers.py[line:104] ERROR NoneType

2017-11-29 15:29:26,295 handlers.py[line:104] ERROR NoneType

2017-11-29 15:29:26,302 handlers.py[line:104] ERROR NoneType

2017-11-29 15:29:26,306 handlers.py[line:104] ERROR NoneType

2017-11-29 15:29:26,425 handlers.py[line:104] ERROR NoneType

2017-11-29 15:29:33,718 handlers.py[line:104] ERROR NoneType

2017-11-29 15:31:35,443 handlers.py[line:104] ERROR NoneType

2017-11-29 15:32:56,132 handlers.py[line:104] ERROR NoneType

2017-11-29 15:32:56,142 handlers.py[line:104] ERROR NoneType

2017-11-29 15:33:11,119 handlers.py[line:104] ERROR NoneType

2017-11-29 15:33:11,120 handlers.py[line:104] ERROR NoneType

2017-11-29 15:33:11,766 handlers.py[line:104] ERROR NoneType

2017-11-29 15:33:11,769 handlers.py[line:104] ERROR NoneType

2017-11-29 15:33:11,771 handlers.py[line:104] ERROR NoneType

2017-11-29 15:33:56,849 handlers.py[line:104] ERROR NoneType

2017-11-29 15:34:57,536 handlers.py[line:104] ERROR NoneType

2017-11-29 15:35:15,487 handlers.py[line:104] ERROR NoneType

2017-11-29 15:36:17,459 handlers.py[line:104] ERROR NoneType

2017-11-29 15:36:17,461 handlers.py[line:104] ERROR NoneType

2017-11-29 15:37:19,080 handlers.py[line:104] ERROR NoneType

2017-11-29 15:39:59,623 handlers.py[line:104] ERROR NoneType

2017-11-29 15:39:59,624 handlers.py[line:104] ERROR NoneType

2017-11-29 15:41:00,300 handlers.py[line:104] ERROR NoneType

2017-11-29 15:42:00,953 handlers.py[line:104] ERROR NoneType

2017-11-29 15:43:01,681 handlers.py[line:104] ERROR NoneType

2017-11-29 15:43:01,686 handlers.py[line:104] ERROR NoneType

2017-11-29 15:44:02,404 handlers.py[line:104] ERROR NoneType

2017-11-29 15:44:53,390 handlers.py[line:104] ERROR NoneType

2017-11-29 15:46:55,100 handlers.py[line:104] ERROR NoneType

2017-11-29 15:49:57,111 handlers.py[line:104] ERROR NoneType

2017-11-29 15:49:57,118 handlers.py[line:104] ERROR NoneType

2017-11-29 15:51:58,543 handlers.py[line:104] ERROR NoneType

2017-11-29 15:51:58,546 handlers.py[line:104] ERROR NoneType

2017-11-29 15:55:00,582 handlers.py[line:104] ERROR NoneType

2017-11-29 15:56:03,529 handlers.py[line:104] ERROR NoneType

2017-11-29 15:56:39,742 handlers.py[line:104] ERROR NoneType

2017-11-29 15:57:04,694 handlers.py[line:104] ERROR NoneType

2017-11-29 15:58:04,980 handlers.py[line:104] ERROR NoneType

2017-11-29 15:58:05,909 handlers.py[line:104] ERROR NoneType

2017-11-29 15:59:06,017 handlers.py[line:104] ERROR NoneType

2017-11-29 16:01:07,369 handlers.py[line:104] ERROR NoneType

2017-11-29 16:02:08,048 handlers.py[line:104] ERROR NoneType

2017-11-29 16:03:09,167 handlers.py[line:104] ERROR NoneType

2017-11-29 16:03:09,169 handlers.py[line:104] ERROR NoneType

2017-11-29 16:03:09,179 handlers.py[line:104] ERROR NoneType

2017-11-29 16:04:09,958 handlers.py[line:104] ERROR NoneType

2017-11-29 16:05:10,663 handlers.py[line:104] ERROR NoneType

2017-11-29 16:06:11,341 handlers.py[line:104] ERROR NoneType

2017-11-29 16:06:11,342 handlers.py[line:104] ERROR NoneType

2017-11-29 16:10:42,005 handlers.py[line:104] ERROR NoneType

2017-11-29 16:11:42,394 handlers.py[line:104] ERROR NoneType

2017-11-29 16:12:43,067 handlers.py[line:104] ERROR NoneType

2017-11-29 16:13:43,696 handlers.py[line:104] ERROR NoneType

2017-11-29 16:13:43,704 handlers.py[line:104] ERROR NoneType

2017-11-29 16:14:44,378 handlers.py[line:104] ERROR NoneType

2017-11-29 16:15:45,120 handlers.py[line:104] ERROR NoneType

2017-11-29 16:16:45,766 handlers.py[line:104] ERROR NoneType

2017-11-29 16:17:18,452 handlers.py[line:104] ERROR NoneType

2017-11-29 16:17:18,465 handlers.py[line:104] ERROR NoneType

2017-11-29 16:17:46,733 handlers.py[line:104] ERROR NoneType

2017-11-29 16:17:46,734 handlers.py[line:104] ERROR NoneType

2017-11-29 16:18:19,733 handlers.py[line:104] ERROR NoneType

2017-11-29 16:18:19,882 handlers.py[line:104] ERROR NoneType

2017-11-29 16:18:19,884 handlers.py[line:104] ERROR NoneType

2017-11-29 16:18:19,885 handlers.py[line:104] ERROR NoneType

2017-11-29 16:18:47,405 handlers.py[line:104] ERROR NoneType

2017-11-29 16:22:22,505 handlers.py[line:104] ERROR NoneType

2017-11-29 16:22:28,467 handlers.py[line:104] ERROR NoneType

2017-11-29 16:23:23,178 handlers.py[line:104] ERROR NoneType

2017-11-29 16:24:23,920 handlers.py[line:104] ERROR NoneType

2017-11-29 16:25:24,711 handlers.py[line:104] ERROR NoneType

2017-11-29 16:26:25,649 handlers.py[line:104] ERROR NoneType

2017-11-29 16:26:25,655 handlers.py[line:104] ERROR NoneType

2017-11-29 16:27:26,320 handlers.py[line:104] ERROR NoneType

2017-11-29 16:28:27,035 handlers.py[line:104] ERROR NoneType

2017-11-29 16:28:27,041 handlers.py[line:104] ERROR NoneType

2017-11-29 16:29:27,661 handlers.py[line:104] ERROR NoneType

2017-11-29 16:30:28,360 handlers.py[line:104] ERROR NoneType

2017-11-29 16:31:29,055 handlers.py[line:104] ERROR NoneType

2017-11-29 16:31:29,062 handlers.py[line:104] ERROR NoneType

2017-11-29 16:32:29,730 handlers.py[line:104] ERROR NoneType

2017-11-29 16:33:30,390 handlers.py[line:104] ERROR NoneType

2017-11-29 16:33:30,391 handlers.py[line:104] ERROR NoneType

2017-11-29 16:33:30,392 handlers.py[line:104] ERROR NoneType

2017-11-29 16:35:31,738 handlers.py[line:104] ERROR NoneType

2017-11-29 16:35:31,742 handlers.py[line:104] ERROR NoneType

2017-11-29 16:37:33,160 handlers.py[line:104] ERROR NoneType

2017-11-29 16:37:33,165 handlers.py[line:104] ERROR NoneType

2017-11-29 16:37:35,099 handlers.py[line:104] ERROR NoneType

2017-11-29 16:39:37,196 handlers.py[line:104] ERROR NoneType

2017-11-29 16:40:37,912 handlers.py[line:104] ERROR NoneType

2017-11-29 16:41:38,630 handlers.py[line:104] ERROR NoneType

2017-11-29 16:41:38,632 handlers.py[line:104] ERROR NoneType

2017-11-29 16:42:39,303 handlers.py[line:104] ERROR NoneType

2017-11-29 16:43:39,941 handlers.py[line:104] ERROR NoneType

2017-11-29 16:44:40,674 handlers.py[line:104] ERROR NoneType

2017-11-29 16:44:50,614 handlers.py[line:104] ERROR NoneType

2017-11-29 16:45:51,180 handlers.py[line:104] ERROR NoneType

2017-11-29 16:46:25,144 handlers.py[line:104] ERROR NoneType

2017-11-29 16:48:25,892 handlers.py[line:104] ERROR NoneType

2017-11-29 16:49:26,570 handlers.py[line:104] ERROR NoneType

2017-11-29 16:51:32,970 handlers.py[line:104] ERROR NoneType

2017-11-29 16:52:33,809 handlers.py[line:104] ERROR NoneType

2017-11-29 16:52:59,761 handlers.py[line:104] ERROR NoneType

2017-11-29 16:54:00,297 handlers.py[line:104] ERROR NoneType

2017-11-29 16:55:01,191 handlers.py[line:104] ERROR NoneType

2017-11-29 16:56:38,148 handlers.py[line:104] ERROR NoneType

2017-11-29 16:57:13,117 handlers.py[line:104] ERROR NoneType

2017-11-29 16:58:13,395 handlers.py[line:104] ERROR NoneType

2017-11-29 16:58:13,397 handlers.py[line:104] ERROR NoneType

2017-11-29 16:59:14,097 handlers.py[line:104] ERROR NoneType

2017-11-29 17:00:14,779 handlers.py[line:104] ERROR NoneType

2017-11-29 17:00:57,757 handlers.py[line:104] ERROR NoneType

2017-11-29 17:00:57,759 handlers.py[line:104] ERROR NoneType

2017-11-29 17:02:42,892 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-11-29 17:02:58,508 handlers.py[line:104] ERROR NoneType

2017-11-29 17:03:59,254 handlers.py[line:104] ERROR NoneType

2017-11-29 17:03:59,257 handlers.py[line:104] ERROR NoneType

2017-11-29 17:04:59,980 handlers.py[line:104] ERROR NoneType

2017-11-29 17:06:51,497 handlers.py[line:104] ERROR NoneType

2017-11-29 17:07:52,196 handlers.py[line:104] ERROR NoneType

2017-11-29 17:07:52,203 handlers.py[line:104] ERROR NoneType

2017-11-29 17:08:52,911 handlers.py[line:104] ERROR NoneType

2017-11-29 17:08:53,834 handlers.py[line:104] ERROR NoneType

2017-11-29 17:09:54,173 handlers.py[line:104] ERROR NoneType

2017-11-29 17:10:56,236 handlers.py[line:104] ERROR NoneType

2017-11-29 17:11:05,248 handlers.py[line:104] ERROR NoneType

2017-11-29 17:11:06,253 handlers.py[line:104] ERROR NoneType

2017-11-29 17:13:07,006 handlers.py[line:104] ERROR NoneType

2017-11-29 17:13:10,937 handlers.py[line:104] ERROR NoneType

2017-11-29 17:15:23,177 handlers.py[line:104] ERROR NoneType

2017-11-29 17:27:00,712 handlers.py[line:104] ERROR NoneType

2017-11-29 17:27:00,811 handlers.py[line:104] ERROR NoneType

2017-11-29 17:28:01,011 handlers.py[line:104] ERROR NoneType

2017-11-29 17:28:01,022 handlers.py[line:104] ERROR NoneType

2017-11-29 17:28:01,748 handlers.py[line:104] ERROR NoneType

2017-11-29 17:28:01,750 handlers.py[line:104] ERROR NoneType

2017-11-29 17:30:28,732 handlers.py[line:104] ERROR NoneType

2017-11-29 17:37:23,949 handlers.py[line:104] ERROR NoneType

2017-11-29 17:38:24,135 handlers.py[line:104] ERROR NoneType

2017-11-29 17:38:24,269 handlers.py[line:104] ERROR NoneType

2017-11-29 18:36:30,830 handlers.py[line:104] ERROR NoneType

2017-11-29 18:36:30,845 handlers.py[line:104] ERROR NoneType

2017-11-29 18:36:30,848 handlers.py[line:104] ERROR NoneType

2017-11-29 18:42:37,217 handlers.py[line:104] ERROR NoneType

2017-11-29 18:42:37,219 handlers.py[line:104] ERROR NoneType

2017-11-29 18:42:37,220 handlers.py[line:104] ERROR NoneType

2017-11-29 18:42:37,221 handlers.py[line:104] ERROR NoneType

2017-11-29 18:42:37,515 handlers.py[line:104] ERROR NoneType

2017-11-29 18:43:41,517 handlers.py[line:104] ERROR NoneType

2017-11-29 18:44:44,003 handlers.py[line:104] ERROR NoneType

2017-11-29 18:48:53,558 handlers.py[line:104] ERROR NoneType

2017-11-29 18:49:56,113 handlers.py[line:104] ERROR NoneType

2017-11-29 18:52:01,934 handlers.py[line:104] ERROR NoneType

2017-11-29 18:54:07,023 handlers.py[line:104] ERROR NoneType

2017-11-29 18:56:03,312 handlers.py[line:104] ERROR NoneType

2017-11-29 18:57:41,136 handlers.py[line:104] ERROR NoneType

2017-11-29 18:58:42,229 handlers.py[line:104] ERROR NoneType

2017-11-29 19:02:18,189 handlers.py[line:104] ERROR NoneType

2017-11-29 19:03:22,183 handlers.py[line:104] ERROR NoneType

2017-11-29 19:07:02,929 handlers.py[line:104] ERROR NoneType

2017-11-29 19:08:05,984 handlers.py[line:104] ERROR NoneType

2017-11-29 19:08:36,508 handlers.py[line:104] ERROR NoneType

2017-11-29 19:09:09,149 handlers.py[line:104] ERROR NoneType

2017-11-29 19:10:10,875 handlers.py[line:104] ERROR NoneType

2017-11-29 19:11:14,437 handlers.py[line:104] ERROR NoneType

2017-11-29 19:11:16,370 handlers.py[line:104] ERROR NoneType

2017-11-29 19:12:19,157 handlers.py[line:104] ERROR NoneType

2017-11-29 19:13:22,967 handlers.py[line:104] ERROR NoneType

2017-11-29 19:14:24,417 handlers.py[line:104] ERROR NoneType

2017-11-29 19:14:25,341 handlers.py[line:104] ERROR NoneType

2017-11-29 19:15:29,265 handlers.py[line:104] ERROR NoneType

2017-11-29 19:26:36,572 handlers.py[line:104] ERROR NoneType

2017-11-29 19:29:39,429 handlers.py[line:104] ERROR NoneType

2017-11-29 19:30:43,736 handlers.py[line:104] ERROR NoneType

2017-11-29 19:36:50,900 handlers.py[line:104] ERROR NoneType

2017-11-29 19:36:50,902 handlers.py[line:104] ERROR NoneType

2017-11-29 19:37:50,980 handlers.py[line:104] ERROR NoneType

2017-11-29 19:38:51,981 handlers.py[line:104] ERROR NoneType

2017-11-29 19:39:52,977 handlers.py[line:104] ERROR NoneType

2017-11-29 19:40:53,972 handlers.py[line:104] ERROR NoneType

2017-11-29 19:40:53,975 handlers.py[line:104] ERROR NoneType

2017-11-29 19:41:55,911 handlers.py[line:104] ERROR NoneType

2017-11-29 19:42:57,926 handlers.py[line:104] ERROR NoneType

2017-11-29 19:45:00,345 handlers.py[line:104] ERROR NoneType

2017-11-29 19:46:02,962 handlers.py[line:104] ERROR NoneType

2017-11-29 19:51:21,331 handlers.py[line:104] ERROR NoneType

2017-11-29 19:53:20,731 handlers.py[line:104] ERROR NoneType

2017-11-29 19:53:20,935 handlers.py[line:104] ERROR NoneType

2017-11-29 19:53:20,936 handlers.py[line:104] ERROR NoneType

2017-11-29 19:53:21,129 handlers.py[line:104] ERROR NoneType

2017-11-29 19:54:30,943 handlers.py[line:104] ERROR NoneType

2017-11-29 19:55:51,691 handlers.py[line:104] ERROR NoneType

2017-11-29 19:55:51,699 handlers.py[line:104] ERROR NoneType

2017-11-29 19:56:44,548 handlers.py[line:104] ERROR NoneType

2017-11-29 19:58:46,989 handlers.py[line:104] ERROR NoneType

2017-11-29 19:58:47,920 handlers.py[line:104] ERROR NoneType

2017-11-29 19:59:11,576 handlers.py[line:104] ERROR NoneType

2017-11-29 19:59:11,585 handlers.py[line:104] ERROR NoneType

2017-11-29 19:59:11,589 handlers.py[line:104] ERROR NoneType

2017-11-29 19:59:48,001 handlers.py[line:104] ERROR NoneType

2017-11-29 20:00:11,883 handlers.py[line:104] ERROR NoneType

2017-11-29 20:00:12,713 handlers.py[line:104] ERROR NoneType

2017-11-29 20:00:49,016 handlers.py[line:104] ERROR NoneType

2017-11-29 20:01:50,016 handlers.py[line:104] ERROR NoneType

2017-11-29 20:02:51,986 handlers.py[line:104] ERROR NoneType

2017-11-29 20:04:06,617 handlers.py[line:104] ERROR NoneType

2017-11-29 20:04:06,630 handlers.py[line:104] ERROR NoneType

2017-11-29 20:04:06,631 handlers.py[line:104] ERROR NoneType

2017-11-29 20:04:08,312 handlers.py[line:104] ERROR NoneType

2017-11-29 20:05:08,105 handlers.py[line:104] ERROR NoneType

2017-11-29 20:05:08,107 handlers.py[line:104] ERROR NoneType

2017-11-29 20:06:08,684 handlers.py[line:104] ERROR NoneType

2017-11-29 20:10:15,364 handlers.py[line:104] ERROR NoneType

2017-11-29 20:11:16,558 handlers.py[line:104] ERROR NoneType

2017-11-29 20:11:16,612 handlers.py[line:104] ERROR NoneType

2017-11-29 20:12:16,850 handlers.py[line:104] ERROR NoneType

2017-11-29 20:12:16,988 handlers.py[line:104] ERROR NoneType

2017-11-29 20:12:17,362 handlers.py[line:104] ERROR NoneType

2017-11-29 20:12:17,490 handlers.py[line:104] ERROR NoneType

2017-11-29 20:16:22,976 handlers.py[line:104] ERROR NoneType

2017-11-29 20:18:23,982 handlers.py[line:104] ERROR NoneType

2017-11-29 20:20:26,490 handlers.py[line:104] ERROR NoneType

2017-11-29 20:21:38,844 handlers.py[line:104] ERROR NoneType

2017-11-29 20:21:57,856 handlers.py[line:104] ERROR NoneType

2017-11-29 20:22:58,769 handlers.py[line:104] ERROR NoneType

2017-11-29 20:25:01,340 handlers.py[line:104] ERROR NoneType

2017-11-29 20:26:32,985 handlers.py[line:104] ERROR NoneType

2017-11-29 20:28:31,998 handlers.py[line:104] ERROR NoneType

2017-11-29 20:29:35,520 handlers.py[line:104] ERROR NoneType

2017-11-29 20:30:37,938 handlers.py[line:104] ERROR NoneType

2017-11-29 20:31:39,008 handlers.py[line:104] ERROR NoneType

2017-11-29 20:32:40,992 handlers.py[line:104] ERROR NoneType

2017-11-29 20:35:05,976 handlers.py[line:104] ERROR NoneType

2017-11-29 20:36:06,598 handlers.py[line:104] ERROR NoneType

2017-11-29 20:38:05,003 handlers.py[line:104] ERROR NoneType

2017-11-29 20:39:24,021 handlers.py[line:104] ERROR NoneType

2017-11-29 20:40:27,243 handlers.py[line:104] ERROR NoneType

2017-11-29 20:41:56,297 handlers.py[line:104] ERROR NoneType

2017-11-29 20:42:58,427 handlers.py[line:104] ERROR NoneType

2017-11-29 20:43:59,238 handlers.py[line:104] ERROR NoneType

2017-11-29 20:45:01,973 handlers.py[line:104] ERROR NoneType

2017-11-29 20:46:02,960 handlers.py[line:104] ERROR NoneType

2017-11-29 20:47:03,562 handlers.py[line:104] ERROR NoneType

2017-11-29 20:47:04,497 handlers.py[line:104] ERROR NoneType

2017-11-29 20:49:07,039 handlers.py[line:104] ERROR NoneType

2017-11-29 20:51:09,973 handlers.py[line:104] ERROR NoneType

2017-11-29 20:51:19,841 handlers.py[line:104] ERROR NoneType

2017-11-29 20:52:10,033 handlers.py[line:104] ERROR NoneType

2017-11-29 20:53:11,033 handlers.py[line:104] ERROR NoneType

2017-11-29 20:54:11,997 handlers.py[line:104] ERROR NoneType

2017-11-29 20:56:31,108 handlers.py[line:104] ERROR NoneType

2017-11-29 20:57:34,736 handlers.py[line:104] ERROR NoneType

2017-11-29 20:59:36,972 handlers.py[line:104] ERROR NoneType

2017-11-29 20:59:36,973 handlers.py[line:104] ERROR NoneType

2017-11-29 21:00:37,971 handlers.py[line:104] ERROR NoneType

2017-11-29 21:01:38,027 handlers.py[line:104] ERROR NoneType

2017-11-29 21:02:39,065 handlers.py[line:104] ERROR NoneType

2017-11-29 21:03:40,966 handlers.py[line:104] ERROR NoneType

2017-11-29 21:04:41,972 handlers.py[line:104] ERROR NoneType

2017-11-29 21:05:42,967 handlers.py[line:104] ERROR NoneType

2017-11-29 21:07:44,026 handlers.py[line:104] ERROR NoneType

2017-11-29 21:08:45,053 handlers.py[line:104] ERROR NoneType

2017-11-29 21:09:29,592 handlers.py[line:104] ERROR NoneType

2017-11-29 21:09:29,594 handlers.py[line:104] ERROR NoneType

2017-11-29 21:10:47,743 handlers.py[line:104] ERROR NoneType

2017-11-29 21:13:01,169 handlers.py[line:104] ERROR NoneType

2017-11-29 21:13:12,334 handlers.py[line:104] ERROR NoneType

2017-11-29 21:13:12,797 handlers.py[line:104] ERROR NoneType

2017-11-29 21:13:12,799 handlers.py[line:104] ERROR NoneType

2017-11-29 21:14:02,162 handlers.py[line:104] ERROR NoneType

2017-11-29 21:16:41,517 handlers.py[line:104] ERROR NoneType

2017-11-29 21:16:41,643 handlers.py[line:104] ERROR NoneType

2017-11-29 21:16:41,645 handlers.py[line:104] ERROR NoneType

2017-11-29 21:17:05,762 handlers.py[line:104] ERROR NoneType

2017-11-29 21:17:41,835 handlers.py[line:104] ERROR NoneType

2017-11-29 21:17:41,964 handlers.py[line:104] ERROR NoneType

2017-11-29 21:17:41,965 handlers.py[line:104] ERROR NoneType

2017-11-29 21:18:06,956 handlers.py[line:104] ERROR NoneType

2017-11-29 21:21:55,879 handlers.py[line:104] ERROR NoneType

2017-11-29 21:22:56,840 handlers.py[line:104] ERROR NoneType

2017-11-29 21:24:06,927 handlers.py[line:104] ERROR NoneType

2017-11-29 21:25:09,418 handlers.py[line:104] ERROR NoneType

2017-11-29 21:26:10,542 handlers.py[line:104] ERROR NoneType

2017-11-29 21:26:11,539 handlers.py[line:104] ERROR NoneType

2017-11-29 21:26:11,656 handlers.py[line:104] ERROR NoneType

2017-11-29 21:26:49,611 handlers.py[line:104] ERROR NoneType

2017-11-29 21:29:52,730 handlers.py[line:104] ERROR NoneType

2017-11-29 21:32:32,082 handlers.py[line:104] ERROR NoneType

2017-11-29 21:33:10,617 handlers.py[line:104] ERROR NoneType

2017-11-29 21:33:33,061 handlers.py[line:104] ERROR NoneType

2017-11-29 21:34:11,728 handlers.py[line:104] ERROR NoneType

2017-11-29 21:35:12,734 handlers.py[line:104] ERROR NoneType

2017-11-29 21:37:00,317 handlers.py[line:104] ERROR NoneType

2017-11-29 21:38:16,662 handlers.py[line:104] ERROR NoneType

2017-11-29 21:39:25,238 handlers.py[line:104] ERROR NoneType

2017-11-29 21:40:18,671 handlers.py[line:104] ERROR NoneType

2017-11-29 21:42:11,564 handlers.py[line:104] ERROR NoneType

2017-11-29 21:45:24,652 handlers.py[line:104] ERROR NoneType

2017-11-29 21:45:51,168 handlers.py[line:104] ERROR NoneType

2017-11-29 21:50:29,660 handlers.py[line:104] ERROR NoneType

2017-11-29 21:51:18,178 handlers.py[line:104] ERROR NoneType

2017-11-29 21:52:31,688 handlers.py[line:104] ERROR NoneType

2017-11-29 21:53:20,029 handlers.py[line:104] ERROR NoneType

2017-11-29 21:54:32,751 handlers.py[line:104] ERROR NoneType

2017-11-29 21:55:31,010 handlers.py[line:104] ERROR NoneType

2017-11-29 21:55:33,741 handlers.py[line:104] ERROR NoneType

2017-11-29 21:57:35,745 handlers.py[line:104] ERROR NoneType

2017-11-29 21:58:36,747 handlers.py[line:104] ERROR NoneType

2017-11-29 21:58:46,038 handlers.py[line:104] ERROR NoneType

2017-11-29 21:59:37,746 handlers.py[line:104] ERROR NoneType

2017-11-29 21:59:48,319 handlers.py[line:104] ERROR NoneType

2017-11-29 22:00:38,726 handlers.py[line:104] ERROR NoneType

2017-11-29 22:01:41,125 handlers.py[line:104] ERROR NoneType

2017-11-29 22:02:40,739 handlers.py[line:104] ERROR NoneType

2017-11-29 22:03:23,142 handlers.py[line:104] ERROR NoneType

2017-11-29 22:04:43,663 handlers.py[line:104] ERROR NoneType

2017-11-29 22:05:47,126 handlers.py[line:104] ERROR NoneType

2017-11-29 22:07:45,743 handlers.py[line:104] ERROR NoneType

2017-11-29 22:09:47,773 handlers.py[line:104] ERROR NoneType

2017-11-29 22:10:48,741 handlers.py[line:104] ERROR NoneType

2017-11-29 22:12:53,676 handlers.py[line:104] ERROR NoneType

2017-11-29 22:12:53,678 handlers.py[line:104] ERROR NoneType

2017-11-29 22:13:54,519 handlers.py[line:104] ERROR NoneType

2017-11-29 22:15:53,745 handlers.py[line:104] ERROR NoneType

2017-11-29 22:16:58,041 handlers.py[line:104] ERROR NoneType

2017-11-29 22:17:49,095 handlers.py[line:104] ERROR NoneType

2017-11-29 22:17:49,101 handlers.py[line:104] ERROR NoneType

2017-11-29 22:17:49,102 handlers.py[line:104] ERROR NoneType

2017-11-29 22:18:00,747 handlers.py[line:104] ERROR NoneType

2017-11-29 22:18:10,052 handlers.py[line:104] ERROR NoneType

2017-11-29 22:18:49,368 handlers.py[line:104] ERROR NoneType

2017-11-29 22:18:49,372 handlers.py[line:104] ERROR NoneType

2017-11-29 22:18:49,376 handlers.py[line:104] ERROR NoneType

2017-11-29 22:18:49,534 handlers.py[line:104] ERROR NoneType

2017-11-29 22:19:02,672 handlers.py[line:104] ERROR NoneType

2017-11-29 22:21:04,706 handlers.py[line:104] ERROR NoneType

2017-11-29 22:24:06,789 handlers.py[line:104] ERROR NoneType

2017-11-29 22:25:12,163 handlers.py[line:104] ERROR NoneType

2017-11-29 22:26:08,949 handlers.py[line:104] ERROR NoneType

2017-11-29 22:26:36,062 handlers.py[line:104] ERROR NoneType

2017-11-29 22:26:45,397 handlers.py[line:104] ERROR NoneType

2017-11-29 22:27:10,670 handlers.py[line:104] ERROR NoneType

2017-11-29 22:27:18,467 handlers.py[line:104] ERROR NoneType

2017-11-29 22:27:37,077 handlers.py[line:104] ERROR NoneType

2017-11-29 22:29:40,972 handlers.py[line:104] ERROR NoneType

2017-11-29 22:30:27,874 handlers.py[line:104] ERROR NoneType

2017-11-29 22:32:44,067 handlers.py[line:104] ERROR NoneType

2017-11-29 22:33:06,018 handlers.py[line:104] ERROR NoneType

2017-11-29 22:33:16,672 handlers.py[line:104] ERROR NoneType

2017-11-29 22:35:18,679 handlers.py[line:104] ERROR NoneType

2017-11-29 22:37:20,733 handlers.py[line:104] ERROR NoneType

2017-11-29 22:37:20,735 app.py[line:498] ERROR Exception occured in one of response middleware handlers
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/app.py", line 495, in handle_request
    response)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 124, in throw
    return self.gen.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/sanic/app.py", line 621, in _run_response_middleware
    _response = await _response
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 124, in throw
    return self.gen.throw(exc)
  File "main_server.py", line 1181, in save_session
    await session_interface.save(request, response)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 124, in throw
    return self.gen.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/sanic_session/redis_session_interface.py", line 100, in save
    await redis_connection.setex(key, self.expiry, val)
  File "/usr/local/lib/python3.5/dist-packages/asyncio_redis/protocol.py", line 676, in wrapper
    result = yield from method(protocol_self, _NoTransaction, *a, **kw)
  File "/usr/local/lib/python3.5/dist-packages/asyncio_redis/protocol.py", line 1135, in _query
    result = yield from self._get_answer(transaction, answer_f, _bypass=_bypass, call=call)
  File "/usr/local/lib/python3.5/dist-packages/asyncio_redis/protocol.py", line 1062, in _get_answer
    result = yield from answer_f
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "uvloop/future.pyx", line 434, in uvloop.loop.BaseTask._fast_wakeup (uvloop/loop.c:114015)
  File "/usr/lib/python3.5/asyncio/futures.py", line 266, in result
    raise CancelledError
concurrent.futures._base.CancelledError
2017-11-29 22:41:17,566 handlers.py[line:104] ERROR NoneType

2017-11-29 22:41:23,748 handlers.py[line:104] ERROR NoneType

2017-11-29 22:44:26,745 handlers.py[line:104] ERROR NoneType

2017-11-29 22:45:22,014 handlers.py[line:104] ERROR NoneType

2017-11-29 22:45:27,749 handlers.py[line:104] ERROR NoneType

2017-11-29 22:46:23,143 handlers.py[line:104] ERROR NoneType

2017-11-29 22:46:29,690 handlers.py[line:104] ERROR NoneType

2017-11-29 22:47:25,036 handlers.py[line:104] ERROR NoneType

2017-11-29 22:49:07,035 handlers.py[line:104] ERROR NoneType

2017-11-29 22:49:32,681 handlers.py[line:104] ERROR NoneType

2017-11-29 22:51:11,489 handlers.py[line:104] ERROR NoneType

2017-11-29 22:51:12,491 handlers.py[line:104] ERROR NoneType

2017-11-29 22:51:33,780 handlers.py[line:104] ERROR NoneType

2017-11-29 22:53:16,306 handlers.py[line:104] ERROR NoneType

2017-11-29 22:53:58,701 handlers.py[line:104] ERROR NoneType

2017-11-29 22:54:19,994 handlers.py[line:104] ERROR NoneType

2017-11-29 22:54:43,167 handlers.py[line:104] ERROR NoneType

2017-11-29 22:54:43,170 handlers.py[line:104] ERROR NoneType

2017-11-29 22:54:43,172 handlers.py[line:104] ERROR NoneType

2017-11-29 22:55:43,488 handlers.py[line:104] ERROR NoneType

2017-11-29 22:55:43,489 handlers.py[line:104] ERROR NoneType

2017-11-29 22:55:43,490 handlers.py[line:104] ERROR NoneType

2017-11-29 22:55:59,746 handlers.py[line:104] ERROR NoneType

2017-11-29 22:56:14,129 handlers.py[line:104] ERROR NoneType

2017-11-29 22:57:17,242 handlers.py[line:104] ERROR NoneType

2017-11-29 22:58:01,757 handlers.py[line:104] ERROR NoneType

2017-11-29 22:59:02,760 handlers.py[line:104] ERROR NoneType

2017-11-29 23:00:03,761 handlers.py[line:104] ERROR NoneType

2017-11-29 23:00:25,171 handlers.py[line:104] ERROR NoneType

2017-11-29 23:01:32,074 handlers.py[line:104] ERROR NoneType

2017-11-29 23:02:06,693 handlers.py[line:104] ERROR NoneType

2017-11-29 23:02:34,400 handlers.py[line:104] ERROR NoneType

2017-11-29 23:04:08,692 handlers.py[line:104] ERROR NoneType

2017-11-29 23:04:39,235 handlers.py[line:104] ERROR NoneType

2017-11-29 23:05:07,196 handlers.py[line:104] ERROR NoneType

2017-11-29 23:06:04,153 handlers.py[line:104] ERROR NoneType

2017-11-29 23:06:04,273 handlers.py[line:104] ERROR NoneType

2017-11-29 23:06:04,274 handlers.py[line:104] ERROR NoneType

2017-11-29 23:06:09,143 handlers.py[line:104] ERROR NoneType

2017-11-29 23:07:04,544 handlers.py[line:104] ERROR NoneType

2017-11-29 23:07:04,548 handlers.py[line:104] ERROR NoneType

2017-11-29 23:07:04,549 handlers.py[line:104] ERROR NoneType

2017-11-29 23:07:11,378 handlers.py[line:104] ERROR NoneType

2017-11-29 23:08:14,644 handlers.py[line:104] ERROR NoneType

2017-11-29 23:08:14,647 handlers.py[line:104] ERROR NoneType

2017-11-29 23:09:17,014 handlers.py[line:104] ERROR NoneType

2017-11-29 23:10:08,532 handlers.py[line:104] ERROR NoneType

2017-11-29 23:10:08,654 handlers.py[line:104] ERROR NoneType

2017-11-29 23:10:08,655 handlers.py[line:104] ERROR NoneType

2017-11-29 23:11:14,754 handlers.py[line:104] ERROR NoneType

2017-11-29 23:11:14,776 handlers.py[line:104] ERROR NoneType

2017-11-29 23:11:14,900 handlers.py[line:104] ERROR NoneType

2017-11-29 23:11:14,901 handlers.py[line:104] ERROR NoneType

2017-11-29 23:11:21,981 handlers.py[line:104] ERROR NoneType

2017-11-29 23:12:15,375 handlers.py[line:104] ERROR NoneType

2017-11-29 23:12:15,379 handlers.py[line:104] ERROR NoneType

2017-11-29 23:12:15,759 handlers.py[line:104] ERROR NoneType

2017-11-29 23:12:24,200 handlers.py[line:104] ERROR NoneType

2017-11-29 23:13:16,756 handlers.py[line:104] ERROR NoneType

2017-11-29 23:14:17,753 handlers.py[line:104] ERROR NoneType

2017-11-29 23:14:31,094 handlers.py[line:104] ERROR NoneType

2017-11-29 23:15:23,045 handlers.py[line:104] ERROR NoneType

2017-11-29 23:16:20,676 handlers.py[line:104] ERROR NoneType

2017-11-29 23:17:10,724 handlers.py[line:104] ERROR NoneType

2017-11-29 23:17:29,531 handlers.py[line:104] ERROR NoneType

2017-11-29 23:17:29,532 handlers.py[line:104] ERROR NoneType

2017-11-29 23:17:29,813 handlers.py[line:104] ERROR NoneType

2017-11-29 23:18:12,117 handlers.py[line:104] ERROR NoneType

2017-11-29 23:19:22,240 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-11-29 23:19:22,788 handlers.py[line:104] ERROR NoneType

2017-11-29 23:19:47,753 handlers.py[line:104] ERROR NoneType

2017-11-29 23:20:23,753 handlers.py[line:104] ERROR NoneType

2017-11-29 23:21:24,765 handlers.py[line:104] ERROR NoneType

2017-11-29 23:21:52,865 handlers.py[line:104] ERROR NoneType

2017-11-29 23:21:52,867 handlers.py[line:104] ERROR NoneType

2017-11-29 23:22:25,766 handlers.py[line:104] ERROR NoneType

2017-11-29 23:22:55,502 handlers.py[line:104] ERROR NoneType

2017-11-29 23:24:27,758 handlers.py[line:104] ERROR NoneType

2017-11-29 23:25:47,838 handlers.py[line:104] ERROR NoneType

2017-11-29 23:26:29,764 handlers.py[line:104] ERROR NoneType

2017-11-29 23:26:49,470 handlers.py[line:104] ERROR NoneType

2017-11-29 23:27:30,777 handlers.py[line:104] ERROR NoneType

2017-11-29 23:27:52,358 handlers.py[line:104] ERROR NoneType

2017-11-29 23:28:31,778 handlers.py[line:104] ERROR NoneType

2017-11-29 23:30:34,704 handlers.py[line:104] ERROR NoneType

2017-11-29 23:30:53,519 handlers.py[line:104] ERROR NoneType

2017-11-29 23:31:55,221 handlers.py[line:104] ERROR NoneType

2017-11-29 23:32:36,739 handlers.py[line:104] ERROR NoneType

2017-11-29 23:32:36,741 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/app.py", line 453, in handle_request
    response = await self._run_request_middleware(request)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 124, in throw
    return self.gen.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/sanic/app.py", line 611, in _run_request_middleware
    response = await response
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 124, in throw
    return self.gen.throw(exc)
  File "main_server.py", line 1174, in add_session_to_request
    await session_interface.open(request)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 124, in throw
    return self.gen.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/sanic_session/redis_session_interface.py", line 61, in open
    val = await redis_connection.get(self.prefix + sid)
  File "/usr/local/lib/python3.5/dist-packages/asyncio_redis/protocol.py", line 676, in wrapper
    result = yield from method(protocol_self, _NoTransaction, *a, **kw)
  File "/usr/local/lib/python3.5/dist-packages/asyncio_redis/protocol.py", line 1135, in _query
    result = yield from self._get_answer(transaction, answer_f, _bypass=_bypass, call=call)
  File "/usr/local/lib/python3.5/dist-packages/asyncio_redis/protocol.py", line 1062, in _get_answer
    result = yield from answer_f
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
concurrent.futures._base.CancelledError

2017-11-29 23:32:36,743 handlers.py[line:120] ERROR Exception occurred while handling uri: "http://39.108.67.178:5000/company/user?index=1"
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/app.py", line 453, in handle_request
    response = await self._run_request_middleware(request)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 124, in throw
    return self.gen.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/sanic/app.py", line 611, in _run_request_middleware
    response = await response
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 124, in throw
    return self.gen.throw(exc)
  File "main_server.py", line 1174, in add_session_to_request
    await session_interface.open(request)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 124, in throw
    return self.gen.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/sanic_session/redis_session_interface.py", line 61, in open
    val = await redis_connection.get(self.prefix + sid)
  File "/usr/local/lib/python3.5/dist-packages/asyncio_redis/protocol.py", line 676, in wrapper
    result = yield from method(protocol_self, _NoTransaction, *a, **kw)
  File "/usr/local/lib/python3.5/dist-packages/asyncio_redis/protocol.py", line 1135, in _query
    result = yield from self._get_answer(transaction, answer_f, _bypass=_bypass, call=call)
  File "/usr/local/lib/python3.5/dist-packages/asyncio_redis/protocol.py", line 1062, in _get_answer
    result = yield from answer_f
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
concurrent.futures._base.CancelledError

2017-11-29 23:32:36,745 server.py[line:217] ERROR Connection lost before response written @ ('180.173.40.150', 61028)
2017-11-29 23:34:00,046 handlers.py[line:104] ERROR NoneType

2017-11-29 23:34:37,752 handlers.py[line:104] ERROR NoneType

2017-11-29 23:35:38,764 handlers.py[line:104] ERROR NoneType

2017-11-29 23:37:37,134 handlers.py[line:104] ERROR NoneType

2017-11-29 23:38:40,034 handlers.py[line:104] ERROR NoneType

2017-11-29 23:39:42,044 handlers.py[line:104] ERROR NoneType

2017-11-29 23:40:43,751 handlers.py[line:104] ERROR NoneType

2017-11-29 23:41:44,772 handlers.py[line:104] ERROR NoneType

2017-11-29 23:42:04,103 handlers.py[line:104] ERROR NoneType

2017-11-29 23:42:04,107 handlers.py[line:104] ERROR NoneType

2017-11-29 23:42:04,117 handlers.py[line:104] ERROR NoneType

2017-11-29 23:43:04,301 handlers.py[line:104] ERROR NoneType

2017-11-29 23:43:04,421 handlers.py[line:104] ERROR NoneType

2017-11-29 23:43:04,428 handlers.py[line:104] ERROR NoneType

2017-11-29 23:43:04,431 handlers.py[line:104] ERROR NoneType

2017-11-29 23:43:09,072 handlers.py[line:104] ERROR NoneType

2017-11-29 23:43:47,707 handlers.py[line:104] ERROR NoneType

2017-11-29 23:44:56,284 handlers.py[line:104] ERROR NoneType

2017-11-29 23:45:57,166 handlers.py[line:104] ERROR NoneType

2017-11-29 23:46:31,388 handlers.py[line:104] ERROR NoneType

2017-11-29 23:46:31,515 handlers.py[line:104] ERROR NoneType

2017-11-29 23:46:31,527 handlers.py[line:104] ERROR NoneType

2017-11-29 23:46:31,528 handlers.py[line:104] ERROR NoneType

2017-11-29 23:47:00,161 handlers.py[line:104] ERROR NoneType

2017-11-29 23:49:52,764 handlers.py[line:104] ERROR NoneType

2017-11-29 23:50:53,768 handlers.py[line:104] ERROR NoneType

2017-11-29 23:50:57,007 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-11-29 23:52:55,766 handlers.py[line:104] ERROR NoneType

2017-11-29 23:54:57,764 handlers.py[line:104] ERROR NoneType

2017-11-29 23:57:00,707 handlers.py[line:104] ERROR NoneType

2017-11-29 23:59:02,720 handlers.py[line:104] ERROR NoneType

2017-11-30 00:01:03,810 handlers.py[line:104] ERROR NoneType

2017-11-30 00:03:05,760 handlers.py[line:104] ERROR NoneType

2017-11-30 00:04:06,758 handlers.py[line:104] ERROR NoneType

2017-11-30 00:05:07,781 handlers.py[line:104] ERROR NoneType

2017-11-30 00:06:08,766 handlers.py[line:104] ERROR NoneType

2017-11-30 00:08:10,777 handlers.py[line:104] ERROR NoneType

2017-11-30 00:09:11,764 handlers.py[line:104] ERROR NoneType

2017-11-30 00:11:14,685 handlers.py[line:104] ERROR NoneType

2017-11-30 00:13:16,762 handlers.py[line:104] ERROR NoneType

2017-11-30 00:13:16,764 app.py[line:498] ERROR Exception occured in one of response middleware handlers
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/app.py", line 495, in handle_request
    response)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 124, in throw
    return self.gen.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/sanic/app.py", line 621, in _run_response_middleware
    _response = await _response
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 124, in throw
    return self.gen.throw(exc)
  File "main_server.py", line 1181, in save_session
    await session_interface.save(request, response)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 124, in throw
    return self.gen.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/sanic_session/redis_session_interface.py", line 100, in save
    await redis_connection.setex(key, self.expiry, val)
  File "/usr/local/lib/python3.5/dist-packages/asyncio_redis/protocol.py", line 676, in wrapper
    result = yield from method(protocol_self, _NoTransaction, *a, **kw)
  File "/usr/local/lib/python3.5/dist-packages/asyncio_redis/protocol.py", line 1135, in _query
    result = yield from self._get_answer(transaction, answer_f, _bypass=_bypass, call=call)
  File "/usr/local/lib/python3.5/dist-packages/asyncio_redis/protocol.py", line 1062, in _get_answer
    result = yield from answer_f
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "uvloop/future.pyx", line 434, in uvloop.loop.BaseTask._fast_wakeup (uvloop/loop.c:114015)
  File "/usr/lib/python3.5/asyncio/futures.py", line 266, in result
    raise CancelledError
concurrent.futures._base.CancelledError
2017-11-30 00:16:18,784 handlers.py[line:104] ERROR NoneType

2017-11-30 00:17:19,764 handlers.py[line:104] ERROR NoneType

2017-11-30 00:18:20,773 handlers.py[line:104] ERROR NoneType

2017-11-30 00:19:21,765 handlers.py[line:104] ERROR NoneType

2017-11-30 00:20:22,762 handlers.py[line:104] ERROR NoneType

2017-11-30 00:21:23,843 handlers.py[line:104] ERROR NoneType

2017-11-30 00:22:24,768 handlers.py[line:104] ERROR NoneType

2017-11-30 00:23:25,767 handlers.py[line:104] ERROR NoneType

2017-11-30 00:26:29,706 handlers.py[line:104] ERROR NoneType

2017-11-30 00:28:31,709 handlers.py[line:104] ERROR NoneType

2017-11-30 00:30:32,802 handlers.py[line:104] ERROR NoneType

2017-11-30 00:31:33,798 handlers.py[line:104] ERROR NoneType

2017-11-30 00:32:34,769 handlers.py[line:104] ERROR NoneType

2017-11-30 00:33:35,777 handlers.py[line:104] ERROR NoneType

2017-11-30 00:34:36,773 handlers.py[line:104] ERROR NoneType

2017-11-30 00:35:37,777 handlers.py[line:104] ERROR NoneType

2017-11-30 00:36:38,775 handlers.py[line:104] ERROR NoneType

2017-11-30 00:39:42,697 handlers.py[line:104] ERROR NoneType

2017-11-30 00:41:44,714 handlers.py[line:104] ERROR NoneType

2017-11-30 00:43:45,796 handlers.py[line:104] ERROR NoneType

2017-11-30 00:45:47,772 handlers.py[line:104] ERROR NoneType

2017-11-30 00:48:51,784 handlers.py[line:104] ERROR NoneType

2017-11-30 00:50:53,771 handlers.py[line:104] ERROR NoneType

2017-11-30 00:51:54,776 handlers.py[line:104] ERROR NoneType

2017-11-30 00:52:55,777 handlers.py[line:104] ERROR NoneType

2017-11-30 00:54:58,704 handlers.py[line:104] ERROR NoneType

2017-11-30 00:56:59,779 handlers.py[line:104] ERROR NoneType

2017-11-30 00:59:01,777 handlers.py[line:104] ERROR NoneType

2017-11-30 01:01:03,776 handlers.py[line:104] ERROR NoneType

2017-11-30 01:02:04,779 handlers.py[line:104] ERROR NoneType

2017-11-30 01:03:05,775 handlers.py[line:104] ERROR NoneType

2017-11-30 09:03:02,400 handlers.py[line:104] ERROR NoneType

2017-11-30 09:03:11,890 handlers.py[line:104] ERROR NoneType

2017-11-30 09:03:11,893 handlers.py[line:104] ERROR NoneType

2017-11-30 09:05:14,474 handlers.py[line:104] ERROR NoneType

2017-11-30 09:05:14,476 handlers.py[line:104] ERROR NoneType

2017-11-30 09:09:51,394 handlers.py[line:104] ERROR NoneType

