2017-11-27 03:30:19,474 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-11-27 09:00:16,060 handlers.py[line:104] ERROR NoneType

2017-11-27 09:12:36,319 handlers.py[line:104] ERROR NoneType

2017-11-27 09:12:36,320 handlers.py[line:104] ERROR NoneType

2017-11-27 09:13:36,701 handlers.py[line:104] ERROR NoneType

2017-11-27 09:14:37,463 handlers.py[line:104] ERROR NoneType

2017-11-27 09:15:38,095 handlers.py[line:104] ERROR NoneType

2017-11-27 09:15:38,095 handlers.py[line:104] ERROR NoneType

2017-11-27 09:16:38,782 handlers.py[line:104] ERROR NoneType

2017-11-27 09:19:55,411 handlers.py[line:104] ERROR NoneType

2017-11-27 09:19:55,414 handlers.py[line:104] ERROR NoneType

2017-11-27 09:22:57,621 handlers.py[line:104] ERROR NoneType

2017-11-27 09:22:57,621 handlers.py[line:104] ERROR NoneType

2017-11-27 09:24:55,929 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-11-27 09:24:58,575 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-11-27 09:24:59,627 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-11-27 09:25:00,686 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-11-27 09:25:01,057 handlers.py[line:104] ERROR NoneType

2017-11-27 09:25:01,742 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-11-27 09:25:03,306 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidURLError: invalid URL

2017-11-27 09:25:04,378 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-11-27 09:25:05,434 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-11-27 09:25:06,487 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-11-27 09:25:07,542 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-11-27 09:27:01,951 handlers.py[line:104] ERROR NoneType

2017-11-27 09:27:01,951 handlers.py[line:104] ERROR NoneType

2017-11-27 09:29:04,306 handlers.py[line:104] ERROR NoneType

2017-11-27 09:31:05,310 handlers.py[line:104] ERROR NoneType

2017-11-27 09:31:32,905 handlers.py[line:104] ERROR NoneType

2017-11-27 09:33:07,652 handlers.py[line:104] ERROR NoneType

2017-11-27 09:33:07,657 handlers.py[line:104] ERROR NoneType

2017-11-27 09:35:09,057 handlers.py[line:104] ERROR NoneType

2017-11-27 09:36:01,560 handlers.py[line:104] ERROR NoneType

2017-11-27 09:36:01,580 handlers.py[line:104] ERROR NoneType

2017-11-27 09:36:01,584 handlers.py[line:104] ERROR NoneType

2017-11-27 09:36:11,743 handlers.py[line:104] ERROR NoneType

2017-11-27 09:37:12,362 handlers.py[line:104] ERROR NoneType

2017-11-27 09:38:13,017 handlers.py[line:104] ERROR NoneType

2017-11-27 09:41:16,511 handlers.py[line:104] ERROR NoneType

2017-11-27 09:47:20,675 handlers.py[line:104] ERROR NoneType

2017-11-27 09:49:22,120 handlers.py[line:104] ERROR NoneType

2017-11-27 09:50:22,870 handlers.py[line:104] ERROR NoneType

2017-11-27 09:52:24,864 handlers.py[line:104] ERROR NoneType

2017-11-27 09:52:24,871 handlers.py[line:104] ERROR NoneType

2017-11-27 09:54:26,338 handlers.py[line:104] ERROR NoneType

2017-11-27 09:55:27,258 handlers.py[line:104] ERROR NoneType

2017-11-27 09:57:28,689 handlers.py[line:104] ERROR NoneType

2017-11-27 09:57:28,692 handlers.py[line:104] ERROR NoneType

2017-11-27 09:58:29,383 handlers.py[line:104] ERROR NoneType

2017-11-27 09:58:29,384 handlers.py[line:104] ERROR NoneType

2017-11-27 10:01:31,540 handlers.py[line:104] ERROR NoneType

2017-11-27 10:03:33,047 handlers.py[line:104] ERROR NoneType

2017-11-27 10:04:34,707 handlers.py[line:104] ERROR NoneType

2017-11-27 10:05:34,913 handlers.py[line:104] ERROR NoneType

2017-11-27 10:05:34,919 handlers.py[line:104] ERROR NoneType

2017-11-27 10:07:36,434 handlers.py[line:104] ERROR NoneType

2017-11-27 10:09:37,865 handlers.py[line:104] ERROR NoneType

2017-11-27 10:11:39,327 handlers.py[line:104] ERROR NoneType

2017-11-27 10:12:40,058 handlers.py[line:104] ERROR NoneType

2017-11-27 10:14:41,473 handlers.py[line:104] ERROR NoneType

2017-11-27 10:15:37,972 handlers.py[line:104] ERROR NoneType

2017-11-27 10:15:39,225 handlers.py[line:104] ERROR NoneType

2017-11-27 10:15:42,696 handlers.py[line:104] ERROR NoneType

2017-11-27 10:16:00,811 handlers.py[line:104] ERROR NoneType

2017-11-27 10:18:45,068 handlers.py[line:104] ERROR NoneType

2017-11-27 10:20:46,699 handlers.py[line:104] ERROR NoneType

2017-11-27 10:22:49,571 handlers.py[line:104] ERROR NoneType

2017-11-27 10:23:50,247 handlers.py[line:104] ERROR NoneType

2017-11-27 10:24:51,107 handlers.py[line:104] ERROR NoneType

2017-11-27 10:25:51,872 handlers.py[line:104] ERROR NoneType

2017-11-27 10:26:52,553 handlers.py[line:104] ERROR NoneType

2017-11-27 10:26:52,555 handlers.py[line:104] ERROR NoneType

2017-11-27 10:28:54,234 handlers.py[line:104] ERROR NoneType

2017-11-27 10:28:54,244 handlers.py[line:104] ERROR NoneType

2017-11-27 10:29:54,972 handlers.py[line:104] ERROR NoneType

2017-11-27 10:31:56,511 handlers.py[line:104] ERROR NoneType

2017-11-27 10:31:56,513 handlers.py[line:104] ERROR NoneType

2017-11-27 10:32:57,341 handlers.py[line:104] ERROR NoneType

2017-11-27 10:34:58,806 handlers.py[line:104] ERROR NoneType

2017-11-27 10:34:58,809 handlers.py[line:104] ERROR NoneType

2017-11-27 10:37:00,326 handlers.py[line:104] ERROR NoneType

2017-11-27 10:37:00,329 handlers.py[line:104] ERROR NoneType

2017-11-27 10:38:02,148 handlers.py[line:104] ERROR NoneType

2017-11-27 10:39:02,349 handlers.py[line:104] ERROR NoneType

2017-11-27 10:39:02,351 handlers.py[line:104] ERROR NoneType

2017-11-27 12:26:09,198 handlers.py[line:104] ERROR NoneType

2017-11-27 12:27:26,790 handlers.py[line:104] ERROR NoneType

2017-11-27 12:32:26,965 handlers.py[line:104] ERROR NoneType

2017-11-27 12:37:16,770 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-11-27 12:54:56,170 handlers.py[line:104] ERROR NoneType

2017-11-27 12:54:56,174 handlers.py[line:104] ERROR NoneType

2017-11-27 12:55:56,470 handlers.py[line:104] ERROR NoneType

2017-11-27 12:55:56,471 handlers.py[line:104] ERROR NoneType

2017-11-27 12:55:56,602 handlers.py[line:104] ERROR NoneType

2017-11-27 13:30:28,914 handlers.py[line:104] ERROR NoneType

2017-11-27 13:35:16,539 handlers.py[line:104] ERROR NoneType

2017-11-27 13:38:18,352 handlers.py[line:104] ERROR NoneType

2017-11-27 13:38:18,354 handlers.py[line:104] ERROR NoneType

2017-11-27 13:40:19,689 handlers.py[line:104] ERROR NoneType

2017-11-27 13:43:21,806 handlers.py[line:104] ERROR NoneType

2017-11-27 13:44:52,439 handlers.py[line:104] ERROR NoneType

2017-11-27 13:45:53,740 handlers.py[line:104] ERROR NoneType

2017-11-27 13:45:53,779 handlers.py[line:104] ERROR NoneType

2017-11-27 13:45:54,664 handlers.py[line:104] ERROR NoneType

2017-11-27 13:48:04,088 handlers.py[line:104] ERROR NoneType

2017-11-27 13:48:25,250 handlers.py[line:104] ERROR NoneType

2017-11-27 13:48:25,251 handlers.py[line:104] ERROR NoneType

2017-11-27 13:48:25,252 handlers.py[line:104] ERROR NoneType

2017-11-27 13:49:02,368 handlers.py[line:104] ERROR NoneType

2017-11-27 13:51:27,359 handlers.py[line:104] ERROR NoneType

2017-11-27 13:51:27,360 handlers.py[line:104] ERROR NoneType

2017-11-27 13:53:28,720 handlers.py[line:104] ERROR NoneType

2017-11-27 13:55:30,052 handlers.py[line:104] ERROR NoneType

2017-11-27 13:58:32,131 handlers.py[line:104] ERROR NoneType

2017-11-27 14:01:34,260 handlers.py[line:104] ERROR NoneType

2017-11-27 14:03:35,618 handlers.py[line:104] ERROR NoneType

2017-11-27 14:06:37,736 handlers.py[line:104] ERROR NoneType

2017-11-27 14:09:39,946 handlers.py[line:104] ERROR NoneType

2017-11-27 14:10:49,600 handlers.py[line:104] ERROR NoneType

2017-11-27 14:10:49,606 handlers.py[line:104] ERROR NoneType

2017-11-27 14:10:49,663 handlers.py[line:104] ERROR NoneType

2017-11-27 14:12:42,086 handlers.py[line:104] ERROR NoneType

2017-11-27 14:13:42,790 handlers.py[line:104] ERROR NoneType

2017-11-27 15:05:38,746 handlers.py[line:104] ERROR NoneType

2017-11-27 15:05:39,865 handlers.py[line:104] ERROR NoneType

2017-11-27 15:05:39,867 handlers.py[line:104] ERROR NoneType

2017-11-27 15:05:39,868 handlers.py[line:104] ERROR NoneType

2017-11-27 15:05:39,869 handlers.py[line:104] ERROR NoneType

2017-11-27 15:28:55,488 handlers.py[line:104] ERROR NoneType

2017-11-27 15:28:55,621 handlers.py[line:104] ERROR NoneType

2017-11-27 15:28:55,622 handlers.py[line:104] ERROR NoneType

2017-11-28 02:40:12,280 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

